# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Default values for iap-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Name of the secret containing the oauth credential keys:
#   client_id
#   client_secret
oauthSecretName:

# If set, will use existing cert from secret, otherwise the conventional name will be used: "endpointServiceName-tls"
tlsSecretName:

# Name of the upstream service to route to.
targetServiceName:

# Port number of upstream service
targetServicePort: 80

# Extensible Service Proxy (ESP) configuration
esp:
  enabled: false
  
  # Name of the Cloud Endpoints service, this will generate a DNS record in the form of:
  #   NAME.endpoints.PROJECT_ID.cloud.goog
  endpointServiceName:

  image:
    repository: gcr.io/endpoints-release/endpoints-runtime
    tag: 1
    pullPolicy: IfNotPresent

envoy:
  enabled: false

  image:
    repository: gcr.io/kubeflow-images-public/envoy
    tag: v20180309-0fb4886b463698702b6a08955045731903a18738
    pullPolicy: IfNotPresent

  # Name of configmap with envoy config, if not specified, a default one will be created.
  # Config must contain a jwt decoder with placeholder values that will be updated:
  # jwts:
  #    audiences: "{JWT_AUDIENCE}"
  #    ...
  configMapName:

  # Key name in configmap containing envoy config
  configMapKey: envoy-config.yaml

  jwtIssuer: https://cloud.google.com/iap
  jwksURI: https://www.gstatic.com/iap/verify/public_key-jwk
  jwtHeaders: x-goog-iap-jwt-assertion

# Name of the project ID for the Cloud Endpoints service
projectID:

ingress:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
  path: /*

cert:
  enabled: true
  issuer: letsencrypt-production
  kind: ClusterIssuer