# This is the same as Dockerfile, but skips `dep ensure`.
# It assumes you already ran that locally.
FROM golang:1.10-alpine AS build

COPY . /go/src/github.com/GoogleCloudPlatform/cloud-endpoints-operator/
WORKDIR /go/src/github.com/GoogleCloudPlatform/cloud-endpoints-operator/cmd/cloud-endpoints-operator
RUN go install

FROM alpine:3.7
RUN apk add --update ca-certificates bash curl
COPY --from=build /go/bin/cloud-endpoints-operator /usr/bin/
CMD ["/usr/bin/cloud-endpoints-operator"]