REVISION: 1
RELEASED: Mon Sep 10 08:14:32 2018
CHART: iap-ingress-0.1.0
USER-SUPPLIED VALUES:
endpointServiceName: iap-tutorial2
esp:
  enabled: true
oauthSecretName: iap-oauth
projectID: cloudjlb-spa
targetServiceName: sample-app2
targetServicePort: 8080

COMPUTED VALUES:
cert:
  enabled: true
  issuer: letsencrypt-production
  kind: ClusterIssuer
endpointServiceName: iap-tutorial2
envoy:
  configMapKey: envoy-config.yaml
  configMapName: null
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: gcr.io/kubeflow-images-public/envoy
    tag: v20180309-0fb4886b463698702b6a08955045731903a18738
  jwksURI: https://www.gstatic.com/iap/verify/public_key-jwk
  jwtHeaders: x-goog-iap-jwt-assertion
  jwtIssuer: https://cloud.google.com/iap
esp:
  enabled: true
  endpointServiceName: null
  image:
    pullPolicy: IfNotPresent
    repository: gcr.io/endpoints-release/endpoints-runtime
    tag: 1
ingress:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
  path: /*
oauthSecretName: iap-oauth
projectID: cloudjlb-spa
targetServiceName: sample-app2
targetServicePort: 8080
tlsSecretName: null

HOOKS:
MANIFEST:

---
# Source: iap-ingress/templates/ingress-bootstrap-job.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iap-tutorial-ingress-iap-ingress-bootstrap
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: iap-tutorial-ingress-iap-ingress-bootstrap
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: iap-tutorial-ingress-iap-ingress-bootstrap
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
subjects:
- kind: ServiceAccount
  name: iap-tutorial-ingress-iap-ingress-bootstrap
  namespace: default
roleRef:
  kind: Role
  name: iap-tutorial-ingress-iap-ingress-bootstrap
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: iap-tutorial-ingress-iap-ingress-bootstrap
spec:
  template:
    metadata:
      labels:
        app: iap-ingress
        chart: iap-ingress-0.1.0
        release: iap-tutorial-ingress
        heritage: Tiller
    spec:
      restartPolicy: OnFailure
      serviceAccountName: iap-tutorial-ingress-iap-ingress-bootstrap
      containers:
      - name: bootstrap
        image: google/cloud-sdk:alpine
        env:  
        - name: NAMESPACE
          value: default
        - name: TLS_SECRET_NAME
          value: iap-tutorial2-ingress-tls
        - name: INGRESS_NAME
          value: iap-tutorial2-ingress
        command:
        - /bin/bash
        - -exc
        - |
          apk add --update openssl

          # This is a workaround until this is resolved: https://github.com/kubernetes/ingress-gce/pull/388
          # The long-term solution is to use a managed SSL certificate on GKE once the feature is GA.

          # Install kubectl
          K8S_VERSION=v1.11.0
          curl -sfSL https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl > /usr/local/bin/kubectl
          chmod +x /usr/local/bin/kubectl

          # The ingress is initially created without a tls spec.
          # Wait until cert-manager generates the certificate using the http-01 challenge on the GCLB ingress.
          # After the certificate is obtained, patch the ingress with the tls spec to enable SSL on the GCLB.

          # Wait for certificate.
          (until kubectl -n ${NAMESPACE} get secret ${TLS_SECRET_NAME} 2>/dev/null; do echo "Waiting for certificate..." ; sleep 2; done)

          kubectl -n ${NAMESPACE} patch ingress ${INGRESS_NAME} --type='json' -p '[{"op": "add", "path": "/spec/tls", "value": [{"secretName": "'${TLS_SECRET_NAME}'"}]}]'

          echo "Done"
---
# Source: iap-ingress/templates/rbac.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iap-tutorial2-proxy
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: iap-tutorial2-proxy
rules:
- apiGroups: ["extensions.gcp.solutions"]
  resources: ["cloudendpoints"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: iap-tutorial2-proxy
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
subjects:
- kind: ServiceAccount
  name: iap-tutorial2-proxy
  namespace: default
roleRef:
  kind: Role
  name: iap-tutorial2-proxy
  apiGroup: rbac.authorization.k8s.io
---
# Source: iap-ingress/templates/proxy-service.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: Service
metadata:
  name: iap-tutorial2-proxy
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"iap-tutorial2-iap"}}'
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: iap-ingress
  type: NodePort
---
# Source: iap-ingress/templates/esp-deployment.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iap-tutorial2-proxy
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iap-ingress
        chart: iap-ingress-0.1.0
        release: iap-tutorial-ingress
        heritage: Tiller
    spec:
      serviceAccountName: iap-tutorial2-proxy
      initContainers:
      - name: init
        image: google/cloud-sdk:alpine
        command:
          - "/bin/bash"
          - -exc
          - |
            # Install kubectl
            K8S_VERSION=v1.11.0
            curl -sfSL https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl > /usr/local/bin/kubectl
            chmod +x /usr/local/bin/kubectl
            SERVICE_VERSION=""
            STATE=""
            until [[ -n "${SERVICE_VERSION}" && "${STATE}" == "IDLE" ]]; do
              echo "Waiting for Cloud Endpoint rollout..."
              SERVICE_VERSION=$(kubectl get cloudep iap-tutorial2 -o jsonpath='{.status.config}')
              STATE=$(kubectl get cloudep iap-tutorial2 -o jsonpath='{.status.stateCurrent}')
              sleep 2
            done
            echo "${SERVICE_VERSION}" > /var/run/proxy-shared/SERVICE_VERSION
        volumeMounts:
        - name: shared
          mountPath: /var/run/proxy-shared
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        command:
        - /bin/bash
        - -exc
        - |
          [[ ! -f /var/run/proxy-shared/SERVICE_VERSION ]] && echo "ERROR: /var/run/proxy-shared/SERVICE_VERSION not found" && exit 1
          export SERVICE_VERSION=$(cat /var/run/proxy-shared/SERVICE_VERSION)

          /usr/sbin/start_esp \
            -p 8080 \
            -z healthz \
            -a sample-app2:8080 \
            -s iap-tutorial2.endpoints.cloudjlb-spa.cloud.goog
            -v ${SERVICE_VERSION}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shared
          mountPath: /var/run/proxy-shared
      volumes:
      - name: shared
        emptyDir:
          medium: Memory
---
# Source: iap-ingress/templates/ingress.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iap-tutorial2-ingress
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    
spec:
  rules:
  - host: iap-tutorial2.endpoints.cloudjlb-spa.cloud.goog
    http:
      paths:
        - path: /*
          backend:
            serviceName: iap-tutorial2-proxy
            servicePort: http


---
# Source: iap-ingress/templates/backend-config.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: iap-tutorial2-iap
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap-oauth
---
# Source: iap-ingress/templates/certificate.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: iap-tutorial2
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
spec:
  secretName: iap-tutorial2-ingress-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: iap-tutorial2.endpoints.cloudjlb-spa.cloud.goog
  dnsNames:
  - iap-tutorial2.endpoints.cloudjlb-spa.cloud.goog
  acme:
    config:
    - http01:
        ingress: iap-tutorial2-ingress
      domains:
      - iap-tutorial2.endpoints.cloudjlb-spa.cloud.goog
---
# Source: iap-ingress/templates/cloud-endpoint.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: extensions.gcp.solutions/v1
kind: CloudEndpoint
metadata:
  name: iap-tutorial2
  labels:
    app: iap-ingress
    chart: iap-ingress-0.1.0
    release: iap-tutorial-ingress
    heritage: Tiller
spec:
  project: cloudjlb-spa
  targetIngress:
    name: iap-tutorial2-ingress
    namespace: default
    jwtServices:
    - iap-tutorial2-proxy

---
# Source: iap-ingress/templates/envoy-configmap.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
# Source: iap-ingress/templates/envoy-deployment.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
